services:
  pm-is:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: pm-is
    volumes:
      - ./:/var/www/html
      - /var/www/vendor
    ports:
      - "8080:80"
    environment:
      - API_PUBLIC_PATH /var/www/html/public
      - API_LOG_PATH /var/www/html/storage/logs
networks:
    default:
        external: true
        name: ict-docker-network